### ISSUE TITLE
warning: unresponsive script

### ISSUE THREAD

**Issue by ufukbs** [ufukbs/onlinekura#4]
When the user enters the same entry more than once (i.e. "ali ali ali") and chooses more than 1 winner (i.e. "2"), script stops running.

User can enter more than one nominee in order to change probability but winners cannot be the same. Also if number of "different" nominees is not higher than number of winners, alert should appear with the text "Farklı aday sayısı, muhtemel kazanan sayısından fazla olmalıdır!"

Thx for your support. 
@ozdemirburak

**Comment by ozdemirburak** [comment]
@ufukbs I'll have a look on that asap.
